
services:
  api:
    build: <user_name>/fastapi
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=host.docker.internal
    # volumes:
    #   - ./app:/usr/src/app/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: 